name: Dev Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt
      - run: chmod +x build.py

      - name: Build
        run: python build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: build/
