name: Dev Build

on:
  push:
    branches:
      - main
    paths:
      - 'cheatgui.js'
      - 'cheatgui.css'
      - '.github/workflows/dev_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@main
        with:
          node-version: '20'

      - run: npm i clean-css uglify-js
      - run: chmod +x build.js

      - name: Build
        run: node build.js

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheatgui-dev-b${{ github.run_number }}
          path: build/
