name: Generate and Deploy JSDoc to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'cheatgui.js'
      - 'README.md'
      - 'jsdoc/**'
      - '.github/workflows/jsdoc-to-gh-pages.yml'

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '20'

      - name: Install JSDoc
        run: npm install -g jsdoc

      - name: Generate JSDoc documentation
        run: jsdoc cheatgui.js -r README.md -c jsdoc/jsdoc.json -d jsdoc/out
      
      - name: Add demo code
        run: |
          mkdir -p jsdoc/out/demo
          cp cheatgui.js jsdoc/out/demo/cheatgui.js
          cp cheatgui.css jsdoc/out/demo/cheatgui.css
          cp index.html jsdoc/out/demo/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          name: documentation
          path: ./jsdoc/out

  deploy:
    needs: deploy-and-build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: documentation
