name: Generate and Deploy JSDoc to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/js/**'
      - 'README.md'
      - 'jsdoc.json'
      - '.github/workflows/jsdoc-to-gh-pages.yml'

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '20'

      - name: Install JSDoc and theme
        run: |
          npm i -g jsdoc
          npm i clean-jsdoc-theme --save-dev

      - name: Generate JSDoc documentation
        run: jsdoc -c jsdoc.json
      
      - name: Build
        run: npm run build
      
      - name: Add demo code
        run: |
          mkdir -p docs/demo
          cp -r build docs/demo
          cp index.html docs/demo/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          name: documentation
          path: ./docs

  deploy:
    needs: deploy-and-build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: documentation
